name: Daily Job Monitor

on:
  workflow_dispatch:

  schedule:
    - cron: '0 13 * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pandas requests pyyaml beautifulsoup4

      - run: python daily_run.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Commit updated baseline
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add baseline/

          git diff --staged --quiet || git commit -m "Update baseline"

          git push